api-version: '1.13'
author: 'Epicnicity322'
depend: [ EpicPluginLib ]
description: 'Allows you to schedule action bars, boss bars, chat messages, commands and titles, every a certain amount of ticks, hours or days.'
main: com.epicnicity322.epicscheduler.EpicScheduler
name: 'EpicScheduler'
softdepend: [ PlaceholderAPI ]
version: '${project.version}'

commands:
  epicscheduler:
    aliases: [ scheduler ]
    description: "EpicScheduler main command."
    permission: epicscheduler.help
  schedule:
    description: "Schedules results to happen in a date."
    permission: epicscheduler.schedule
  unschedule:
    description: "Un-schedules previous scheduled results"
    permission: epicscheduler.schedule

permissions:
  epicscheduler.op:
    description: All permissions of EpicScheduler.
    default: op
    children:
      epicscheduler.help: true
      epicscheduler.reset: true
      epicscheduler.schedule: true